# Generated by Django 4.1 on 2023-08-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usercustomer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustomer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usercustomer',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='usercustomer',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
