# Generated by Django 4.1 on 2023-08-04 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_usercustomer_email_alter_usercustomer_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercustomer',
            name='username',
        ),
    ]
