# Generated by Django 4.2.1 on 2023-11-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_usercustomer_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustomer',
            name='ci',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usercustomer',
            name='phone',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='usercustomer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
