# Generated by Django 4.2.1 on 2024-04-28 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.department')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tasks_projects_t',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('is_pending', models.BooleanField(default=True)),
                ('porcentage_task', models.PositiveIntegerField(default=0)),
                ('start_day', models.DateField()),
                ('end_day', models.DateField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.department')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='task.project_tasks')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tasks_task_t',
            },
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('is_pending', models.BooleanField(default=True)),
                ('porcentage_task', models.PositiveIntegerField(default=0)),
                ('start_day', models.DateField()),
                ('end_day', models.DateField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.department')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='task.project_tasks')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='task.task')),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tasks_task_history_t',
            },
        ),
    ]
