# Generated by Django 4.2.1 on 2023-06-12 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_company_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('start_day', models.DateField()),
                ('end_day', models.DateField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.department')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tasks_task_history_t',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('start_day', models.DateField()),
                ('end_day', models.DateField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.department')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tasks_task_t',
            },
        ),
    ]
