# Generated by Django 4.2.1 on 2023-06-14 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='users',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='taskhistory',
            old_name='users',
            new_name='user',
        ),
    ]
