# Generated by Django 4.2.1 on 2023-06-14 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_rename_users_task_user_rename_users_taskhistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhistory',
            name='is_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
