# Generated by Django 4.2.1 on 2023-06-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_taskhistory_is_pending_taskhistory_is_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
