# Generated by Django 4.2.1 on 2023-06-16 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_task_is_pending_task_is_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskhistory',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='is_started',
            field=models.BooleanField(default=True),
        ),
    ]
