# Generated by Django 4.2.1 on 2023-06-16 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_taskhistory_is_pending_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_started',
            field=models.BooleanField(default=True),
        ),
    ]
