# Generated by Django 4.2.1 on 2023-06-16 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_task_is_pending_alter_task_is_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
