# Generated by Django 4.2.1 on 2023-06-16 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_task_description_taskhistory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhistory',
            name='taks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='task.task'),
        ),
    ]
