# Generated by Django 4.2.1 on 2023-06-16 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_taskhistory_taks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskhistory',
            old_name='taks',
            new_name='task',
        ),
    ]
