# Generated by Django 4.2.1 on 2023-07-09 22:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0009_rename_taks_taskhistory_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskhistory',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
