# Generated by Django 4.2.1 on 2023-07-31 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usercustomer_is_active'),
        ('task', '0010_alter_taskhistory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ManyToManyField(to='users.usercustomer'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='user',
            field=models.ManyToManyField(blank=True, to='users.usercustomer'),
        ),
    ]
