# Generated by Django 4.1 on 2023-08-07 13:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_usercustomer_username'),
        ('companies', '0006_alter_company_users_alter_department_user'),
        ('task', '0011_alter_task_user_alter_taskhistory_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatsTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('text', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=pathlib.PurePosixPath('/home/pegaso/projects_gabriel/Sistema_gestion_actividades/media'))),
                ('images', models.ImageField(blank=True, null=True, upload_to=pathlib.PurePosixPath('/home/pegaso/projects_gabriel/Sistema_gestion_actividades/media'))),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_closed', models.DateField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.department')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='users.usercustomer')),
            ],
            options={
                'db_table': 'tasks_chats',
            },
        ),
    ]
