# Generated by Django 4.1 on 2023-08-07 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_chatstasks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatsTasks',
        ),
    ]
