# Generated by Django 4.2.1 on 2023-09-10 17:15

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_chatstasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatstasks',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=pathlib.PureWindowsPath('C:/Users/gabri/OneDrive/Documentos/Repositorios-github/sistema_gestion_actividades/Sistema_gestion_actividades/media')),
        ),
        migrations.AlterField(
            model_name='chatstasks',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=pathlib.PureWindowsPath('C:/Users/gabri/OneDrive/Documentos/Repositorios-github/sistema_gestion_actividades/Sistema_gestion_actividades/media')),
        ),
    ]
