# Generated by Django 4.2.1 on 2023-10-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0015_alter_chatstasks_file_alter_chatstasks_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_started',
        ),
        migrations.RemoveField(
            model_name='taskhistory',
            name='is_started',
        ),
        migrations.AddField(
            model_name='task',
            name='percentage_task',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='percentage_task',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
