# Generated by Django 4.2.1 on 2023-10-09 18:41

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0016_remove_task_is_started_remove_taskhistory_is_started_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='percentage_task',
            new_name='porcentage_task',
        ),
        migrations.RenameField(
            model_name='taskhistory',
            old_name='percentage_task',
            new_name='porcentage_task',
        ),
        migrations.AlterField(
            model_name='chatstasks',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=pathlib.PureWindowsPath('C:/Users/gabriel.carvajal/Documents/GitHub/sistema_gestion_actividades/Sistema_gestion_actividades/media')),
        ),
        migrations.AlterField(
            model_name='chatstasks',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=pathlib.PureWindowsPath('C:/Users/gabriel.carvajal/Documents/GitHub/sistema_gestion_actividades/Sistema_gestion_actividades/media')),
        ),
    ]
