# Generated by Django 4.2.1 on 2023-12-03 00:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_usercustomer_ci_usercustomer_phone_and_more'),
        ('companies', '0007_remove_company_users_remove_department_user_and_more'),
        ('task', '0017_rename_percentage_task_task_porcentage_task_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.department')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.usercustomer')),
            ],
            options={
                'db_table': 'tasks_projects_t',
            },
        ),
        migrations.DeleteModel(
            name='ChatsTasks',
        ),
    ]
