# Generated by Django 4.2.1 on 2023-12-03 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0018_project_tasks_delete_chatstasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='task.project_tasks'),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='task.project_tasks'),
        ),
    ]
