# Generated by Django 4.2.1 on 2023-07-31 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usercustomer_is_active'),
        ('companies', '0005_remove_roles_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='users',
            field=models.ManyToManyField(to='users.usercustomer'),
        ),
        migrations.AlterField(
            model_name='department',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.usercustomer'),
        ),
    ]
