# Generated by Django 4.2.1 on 2023-11-26 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_usercustomer_ci_usercustomer_phone_and_more'),
        ('companies', '0006_alter_company_users_alter_department_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='users',
        ),
        migrations.RemoveField(
            model_name='department',
            name='user',
        ),
        migrations.AddField(
            model_name='department',
            name='user',
            field=models.ManyToManyField(blank=True, to='users.usercustomer'),
        ),
    ]
